version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    # - dupl # TODO: enable in future
    # - errorlint # TODO: enable in future
    # - gocognit # TODO: enable in future
    # - cyclop # TODO: enable in future
    # - paralleltest # TODO: enable in future
    # - nestif # TODO: enable in future
    # - maintidx # TODO: enable in future
    # - exhaustive # TODO: enable in future
    # - nilnil # TODO: enable in future
    # - gochecknoglobals # TODO: enable in future
    # - goerr113 # TODO: enable in future
    # - ireturn # TODO: enable in future
    - errchkjson
    - errname
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - lll
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Debug
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Debugf
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Info
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Infof
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Warning
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Warningf
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Error
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Errorf
        - (*github.com/src-doo/netbox-ssot/internal/logger.Logger).Output
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: G402
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 20
formatters:
  enable:
    - gci
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
