// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapExaGrid = map[string]*DeviceData{
    "EX10": {
        Manufacturer: "ExaGrid",
        Model: "EX10",
        Slug: "exagrid-ex10",
        UHeight: 2,
        PartNumber: "EX10-SEC",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GbE-1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GbE-2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "SPF-1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-3", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-4", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "iLO", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "EX18": {
        Manufacturer: "ExaGrid",
        Model: "EX18",
        Slug: "exagrid-ex18",
        UHeight: 2,
        PartNumber: "EX18-SEC",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GbE-1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GbE-2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "SPF-1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-3", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-4", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "iLO", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "EX189": {
        Manufacturer: "ExaGrid",
        Model: "EX189",
        Slug: "exagrid-ex189",
        UHeight: 2,
        PartNumber: "EX189-SEC",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GbE-1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GbE-2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "SPF-1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-5", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-6", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SPF-7", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-8", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "iLO", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "EX27": {
        Manufacturer: "ExaGrid",
        Model: "EX27",
        Slug: "exagrid-ex27",
        UHeight: 2,
        PartNumber: "EX27-SEC",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GbE-1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GbE-2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "SPF-1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-3", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-4", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "iLO", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "EX36": {
        Manufacturer: "ExaGrid",
        Model: "EX36",
        Slug: "exagrid-ex36",
        UHeight: 2,
        PartNumber: "EX36-SEC",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GbE-1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GbE-2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "SPF-1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-3", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-4", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "iLO", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "EX54": {
        Manufacturer: "ExaGrid",
        Model: "EX54",
        Slug: "exagrid-ex54",
        UHeight: 2,
        PartNumber: "EX54-SEC",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GbE-1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GbE-2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "SPF-1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-5", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-6", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SPF-7", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-8", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "iLO", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "EX84": {
        Manufacturer: "ExaGrid",
        Model: "EX84",
        Slug: "exagrid-ex84",
        UHeight: 2,
        PartNumber: "EX84-SEC",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GbE-1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GbE-2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "SPF-1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SFP-4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SPF-5", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-6", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SPF-7", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "SFP-8", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "iLO", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
}
