// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapCyberPower = map[string]*DeviceData{
    "CP1500PFCLCD": {
        Manufacturer: "CyberPower",
        Model: "CP1500PFCLCD",
        Slug: "cyberpower-cps1500pfclcd",
        UHeight: 0,
        PartNumber: "cps1500pfclcd",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power Port 1", Label: "", Type: "nema-5-15p", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Surge 1", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge 2", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge 3", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge 4", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge 5", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge 6", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge &#43; Battery 1", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge &#43; Battery 2", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge &#43; Battery 3", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge &#43; Battery 4", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge &#43; Battery 5", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Surge &#43; Battery 6", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "CPS-1220RMS": {
        Manufacturer: "CyberPower",
        Model: "CPS-1220RMS",
        Slug: "cyberpower-cps-1220rms",
        UHeight: 1,
        PartNumber: "cps1220rms",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power Port 1", Label: "", Type: "nema-5-20p", MaximumDraw: 1800, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Front Outlet 1", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front Outlet 2", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 1", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 2", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 3", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 4", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 5", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 6", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 7", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 8", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 9", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 10", Type: "nema-5-20r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "CPS1215RM": {
        Manufacturer: "CyberPower",
        Model: "CPS1215RM",
        Slug: "cyberpower-cps1215rm",
        UHeight: 1,
        PartNumber: "cps1215rm",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power Port 1", Label: "", Type: "nema-5-15p", MaximumDraw: 1800, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Rear Outlet 1", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 2", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 3", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 4", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 5", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 6", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 7", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 8", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 9", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 10", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "CPS1215RMS": {
        Manufacturer: "CyberPower",
        Model: "CPS1215RMS",
        Slug: "cyberpower-cps1215rms",
        UHeight: 1,
        PartNumber: "cps1215rms",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power Port 1", Label: "", Type: "nema-5-15p", MaximumDraw: 1800, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Front Outlet 1", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front Outlet 2", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front Outlet 3", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front Outlet 4", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front Outlet 5", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front Outlet 6", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 1", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 2", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 3", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 4", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 5", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 6", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "OR1000LCDRM1U": {
        Manufacturer: "CyberPower",
        Model: "OR1000LCDRM1U",
        Slug: "cyberpower-or1000lcdrm1u",
        UHeight: 1,
        PartNumber: "or1000lcdrm1u",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial Port I", Type: "de-9", Label: "", Poe: false },
            { Name: "Serial Port II", Type: "de-9", Label: "", Poe: false },
            { Name: "USB", Type: "usb-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "AC Input", Label: "", Type: "nema-5-15p", MaximumDraw: 600, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "power1", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "power2", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "power3", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "power4", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "power5", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "power6", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: true },
        },
    },
    "OR1500LCDRTXL2U": {
        Manufacturer: "CyberPower",
        Model: "OR1500LCDRTXL2U",
        Slug: "cyberpower-or1500lcdrtxl2u",
        UHeight: 2,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial Port I", Type: "de-9", Label: "", Poe: false },
            { Name: "Serial Port II", Type: "de-9", Label: "", Poe: false },
            { Name: "USB", Type: "usb-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "AC Input", Label: "", Type: "nema-5-15p", MaximumDraw: 1125, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Right Top 1", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Right Top 2", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Right Bottom 1", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Right Bottom 2", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Top 1", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Top 2", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Bottom 1", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Bottom 2", Type: "nema-5-15r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "1", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "OR2200LCDRT2U": {
        Manufacturer: "CyberPower",
        Model: "OR2200LCDRT2U",
        Slug: "cyberpower-or2200lcdrt2u",
        UHeight: 2,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial Port I", Type: "de-9", Label: "", Poe: false },
            { Name: "Serial Port II", Type: "de-9", Label: "", Poe: false },
            { Name: "USB", Type: "usb-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "AC Input", Label: "", Type: "nema-5-20p", MaximumDraw: 1320, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Right Top 1", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Right Top 2", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Right Bottom 1", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Right Bottom 2", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Top 1", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Top 2", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Bottom 1", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Left Bottom 2", Type: "nema-5-20r", Label: "", PowerPort: "AC Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "PDU15M2F12R": {
        Manufacturer: "CyberPower",
        Model: "PDU15M2F12R",
        Slug: "cyberpower-pdu15m2f12r",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power Port 1", Label: "", Type: "nema-5-15p", MaximumDraw: 1800, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Front Outlet 1", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front Outlet 2", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 1", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 2", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 3", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 4", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 5", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 6", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 7", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 8", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 9", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 10", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 11", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear Outlet 12", Type: "nema-5-15r", Label: "", PowerPort: "Power Port 1", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
