// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapIBM = map[string]*DeviceData{
    "BladeCenter H": {
        Manufacturer: "IBM",
        Model: "BladeCenter H",
        Slug: "ibm-bladecenter-h",
        UHeight: 9,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU0", Label: "", Position: "0" },
            { Name: "PSU1", Label: "", Position: "1" },
            { Name: "PSU2", Label: "", Position: "2" },
            { Name: "PSU3", Label: "", Position: "3" },
        },
			  DeviceBays: []DeviceBay{
            { Name: "Server Bay 1", Label: "" },
            { Name: "Server Bay 2", Label: "" },
            { Name: "Server Bay 3", Label: "" },
            { Name: "Server Bay 4", Label: "" },
            { Name: "Server Bay 5", Label: "" },
            { Name: "Server Bay 6", Label: "" },
            { Name: "Server Bay 7", Label: "" },
            { Name: "Server Bay 8", Label: "" },
            { Name: "Server Bay 9", Label: "" },
            { Name: "Server Bay 10", Label: "" },
            { Name: "Server Bay 11", Label: "" },
            { Name: "Server Bay 12", Label: "" },
            { Name: "Server Bay 13", Label: "" },
            { Name: "Server Bay 14", Label: "" },
            { Name: "I/O Module Bay 1", Label: "" },
            { Name: "I/O Module Bay 2", Label: "" },
            { Name: "I/O Module Bay 3", Label: "" },
            { Name: "I/O Module Bay 4", Label: "" },
            { Name: "I/O Module Bay 5", Label: "" },
            { Name: "I/O Module Bay 6", Label: "" },
            { Name: "I/O Module Bay 7 (High-speed)", Label: "" },
            { Name: "I/O Module Bay 8 (High-speed)", Label: "" },
            { Name: "I/O Module Bay 9 (High-speed)", Label: "" },
            { Name: "I/O Module Bay 10 (High-speed)", Label: "" },
            { Name: "Management Module Bay 1", Label: "" },
            { Name: "Management Module Bay 2", Label: "" },
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "BladeCenter HS22": {
        Manufacturer: "IBM",
        Model: "BladeCenter HS22",
        Slug: "ibm-bladecenter-hs22",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "System x3550": {
        Manufacturer: "IBM",
        Model: "System x3550",
        Slug: "ibm-system-x3550",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "Front USB1", Type: "usb-a", Label: "" },
            { Name: "Front USB2", Type: "usb-a", Label: "" },
            { Name: "Rear USB1", Type: "usb-a", Label: "" },
            { Name: "Rear USB2", Type: "usb-a", Label: "" },
        },
        PowerPorts: []PowerPort{
            { Name: "Power 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 670, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "TenGig-E 1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "TenGig-E 2", Label: "", Type: "10gbase-t", MgmtOnly: false },
        },
    },
    "eServer x226": {
        Manufacturer: "IBM",
        Model: "eServer x226",
        Slug: "ibm-eserver-x226",
        UHeight: 5,
        PartNumber: "86482DG",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU1", Label: "", Type: "iec-60320-c14", MaximumDraw: 514, AllocatedDraw: 0 },
            { Name: "PSU2", Label: "", Type: "iec-60320-c14", MaximumDraw: 514, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Gig-E 1", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
