// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapPCEngines = map[string]*DeviceData{
    "APU": {
        Manufacturer: "PC Engines",
        Model: "APU",
        Slug: "pc-engines-apu1",
        UHeight: 0,
        PartNumber: "apu1",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "ttyS0", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Input", Label: "", Type: "dc-terminal", MaximumDraw: 12, AllocatedDraw: 6 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "re0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "re1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "re2", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "APU2": {
        Manufacturer: "PC Engines",
        Model: "APU2",
        Slug: "pc-engines-apu2",
        UHeight: 1,
        PartNumber: "apu2",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "ttyS0", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Input", Label: "", Type: "dc-terminal", MaximumDraw: 12, AllocatedDraw: 6 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "igb0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "igb1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "igb2", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "APU4": {
        Manufacturer: "PC Engines",
        Model: "APU4",
        Slug: "pc-engines-apu4",
        UHeight: 0,
        PartNumber: "apu4",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "ttyS0", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Input", Label: "", Type: "dc-terminal", MaximumDraw: 12, AllocatedDraw: 6 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "igb0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "igb1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "igb2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "igb3", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "APU6": {
        Manufacturer: "PC Engines",
        Model: "APU6",
        Slug: "pc-engines-apu6",
        UHeight: 0,
        PartNumber: "apu6",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 16,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "ttyS0", Type: "usb-micro-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Input", Label: "", Type: "dc-terminal", MaximumDraw: 12, AllocatedDraw: 6 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "USB1", Label: "", Type: "other", MgmtOnly: false },
            { Name: "USB2", Label: "", Type: "other", MgmtOnly: false },
        },
    },
}
