// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapSonicWall = map[string]*DeviceData{
    "NSa 220": {
        Manufacturer: "SonicWall",
        Model: "NSa 220",
        Slug: "sonicwall-nsa-220",
        UHeight: 1,
        PartNumber: "NSA220",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1.95,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC", Label: "", Type: "dc-terminal", MaximumDraw: 15, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "NSa 2650": {
        Manufacturer: "SonicWall",
        Model: "NSa 2650",
        Slug: "sonicwall-nsa-2650",
        UHeight: 1,
        PartNumber: "NSA2650",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "NSa 2700": {
        Manufacturer: "SonicWall",
        Model: "NSa 2700",
        Slug: "sonicwall-nsa-2700",
        UHeight: 1,
        PartNumber: "NSA2700",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "NSa 3650": {
        Manufacturer: "SonicWall",
        Model: "NSa 3650",
        Slug: "sonicwall-nsa-3650",
        UHeight: 1,
        PartNumber: "NSA3650",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "NSa 3700": {
        Manufacturer: "SonicWall",
        Model: "NSa 3700",
        Slug: "sonicwall-nsa-3700",
        UHeight: 1,
        PartNumber: "NSA3700",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X26", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X27", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X28", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X29", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X30", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X31", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X32", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X33", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "NSa 4650": {
        Manufacturer: "SonicWall",
        Model: "NSa 4650",
        Slug: "sonicwall-nsa-4650",
        UHeight: 1,
        PartNumber: "NSA4650",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "NSa 4700": {
        Manufacturer: "SonicWall",
        Model: "NSa 4700",
        Slug: "sonicwall-nsa-4700",
        UHeight: 1,
        PartNumber: "NSA4700",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X26", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X27", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X28", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X29", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "NSa 5650": {
        Manufacturer: "SonicWall",
        Model: "NSa 5650",
        Slug: "sonicwall-nsa-5650",
        UHeight: 1,
        PartNumber: "NSA5650",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X26", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X27", Label: "", Type: "10gbase-t", MgmtOnly: false },
        },
    },
    "NSa 5700": {
        Manufacturer: "SonicWall",
        Model: "NSa 5700",
        Slug: "sonicwall-nsa-5700",
        UHeight: 1,
        PartNumber: "NSA5700",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X26", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X27", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X28", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X29", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X30", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X31", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "NSa 6700": {
        Manufacturer: "SonicWall",
        Model: "NSa 6700",
        Slug: "sonicwall-nsa-6700",
        UHeight: 1,
        PartNumber: "NSA6700",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 3", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X26", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X27", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X28", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X29", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X30", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X31", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X32", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "X33", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
        },
    },
    "NSsp 13700": {
        Manufacturer: "SonicWall",
        Model: "NSsp 13700",
        Slug: "sonicwall-nssp-13700",
        UHeight: 1,
        PartNumber: "NSSP13700",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 3", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X26", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X27", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X28", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X29", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X30", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X31", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "X32", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "X33", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
        },
    },
    "NSsp 15700": {
        Manufacturer: "SonicWall",
        Model: "NSsp 15700",
        Slug: "sonicwall-nssp-15700",
        UHeight: 2,
        PartNumber: "NSSP15700",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU Slot 1", Label: "", Position: "1" },
            { Name: "PSU Slot 2", Label: "", Position: "2" },
            { Name: "Expansion Module", Label: "", Position: "" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
            { Name: "Storage-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Storage-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Storage-Module 3", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Storage-Module 4", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 1", Label: "", Manufacturer: "SonicWall", PartID: "" },
            { Name: "Fan-Module 2", Label: "", Manufacturer: "SonicWall", PartID: "" },
        },
        Interfaces: []Interface{
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "X0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X10", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X11", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X12", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X13", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X14", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X15", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X16", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "X17", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "X18", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "X19", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "X20", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "X21", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "X22", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "X23", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "X24", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "X25", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
        },
    },
    "SOHO": {
        Manufacturer: "SonicWall",
        Model: "SOHO",
        Slug: "sonicwall-soho",
        UHeight: 1,
        PartNumber: "SOHO",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SOHOW": {
        Manufacturer: "SonicWall",
        Model: "SOHOW",
        Slug: "sonicwall-sohow",
        UHeight: 1,
        PartNumber: "SOHOW",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11n", MgmtOnly: false },
        },
    },
    "TZ250": {
        Manufacturer: "SonicWall",
        Model: "TZ250",
        Slug: "sonicwall-tz250",
        UHeight: 1,
        PartNumber: "TZ250",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ250W": {
        Manufacturer: "SonicWall",
        Model: "TZ250W",
        Slug: "sonicwall-tz250w",
        UHeight: 1,
        PartNumber: "TZ250W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11n", MgmtOnly: false },
        },
    },
    "TZ270": {
        Manufacturer: "SonicWall",
        Model: "TZ270",
        Slug: "sonicwall-tz270",
        UHeight: 1,
        PartNumber: "TZ270",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ270W": {
        Manufacturer: "SonicWall",
        Model: "TZ270W",
        Slug: "sonicwall-tz270w",
        UHeight: 1,
        PartNumber: "TZ270W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ300": {
        Manufacturer: "SonicWall",
        Model: "TZ300",
        Slug: "sonicwall-tz300",
        UHeight: 1,
        PartNumber: "TZ300",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ300P": {
        Manufacturer: "SonicWall",
        Model: "TZ300P",
        Slug: "sonicwall-tz300p",
        UHeight: 1,
        PartNumber: "TZ300P",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 65, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ300W": {
        Manufacturer: "SonicWall",
        Model: "TZ300W",
        Slug: "sonicwall-tz300w",
        UHeight: 1,
        PartNumber: "TZ300W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ350": {
        Manufacturer: "SonicWall",
        Model: "TZ350",
        Slug: "sonicwall-tz350",
        UHeight: 1,
        PartNumber: "TZ350",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ350W": {
        Manufacturer: "SonicWall",
        Model: "TZ350W",
        Slug: "sonicwall-tz350w",
        UHeight: 1,
        PartNumber: "TZ350W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ370": {
        Manufacturer: "SonicWall",
        Model: "TZ370",
        Slug: "sonicwall-tz370",
        UHeight: 1,
        PartNumber: "TZ370",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ370W": {
        Manufacturer: "SonicWall",
        Model: "TZ370W",
        Slug: "sonicwall-tz370w",
        UHeight: 1,
        PartNumber: "TZ370W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ400": {
        Manufacturer: "SonicWall",
        Model: "TZ400",
        Slug: "sonicwall-tz400",
        UHeight: 1,
        PartNumber: "TZ400",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ400W": {
        Manufacturer: "SonicWall",
        Model: "TZ400W",
        Slug: "sonicwall-tz400w",
        UHeight: 1,
        PartNumber: "TZ400W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ470": {
        Manufacturer: "SonicWall",
        Model: "TZ470",
        Slug: "sonicwall-tz470",
        UHeight: 1,
        PartNumber: "TZ470",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "TZ470W": {
        Manufacturer: "SonicWall",
        Model: "TZ470W",
        Slug: "sonicwall-tz470w",
        UHeight: 1,
        PartNumber: "TZ470W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ500": {
        Manufacturer: "SonicWall",
        Model: "TZ500",
        Slug: "sonicwall-tz500",
        UHeight: 1,
        PartNumber: "TZ500",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ500W": {
        Manufacturer: "SonicWall",
        Model: "TZ500W",
        Slug: "sonicwall-tz500w",
        UHeight: 1,
        PartNumber: "TZ500W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 36, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ570": {
        Manufacturer: "SonicWall",
        Model: "TZ570",
        Slug: "sonicwall-tz570",
        UHeight: 1,
        PartNumber: "TZ570",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 60, AllocatedDraw: 0 },
            { Name: "PSU 2", Label: "", Type: "iec-60320-c14", MaximumDraw: 60, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "TZ570P": {
        Manufacturer: "SonicWall",
        Model: "TZ570P",
        Slug: "sonicwall-tz570p",
        UHeight: 1,
        PartNumber: "TZ570P",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 180, AllocatedDraw: 0 },
            { Name: "PSU 2", Label: "", Type: "iec-60320-c14", MaximumDraw: 180, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "TZ570W": {
        Manufacturer: "SonicWall",
        Model: "TZ570W",
        Slug: "sonicwall-tz570w",
        UHeight: 1,
        PartNumber: "TZ570W",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 60, AllocatedDraw: 0 },
            { Name: "PSU 2", Label: "", Type: "iec-60320-c14", MaximumDraw: 60, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "W0", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "TZ600": {
        Manufacturer: "SonicWall",
        Model: "TZ600",
        Slug: "sonicwall-tz600",
        UHeight: 1,
        PartNumber: "TZ600",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 60, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ600P": {
        Manufacturer: "SonicWall",
        Model: "TZ600P",
        Slug: "sonicwall-tz600p",
        UHeight: 1,
        PartNumber: "TZ600P",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 180, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TZ670": {
        Manufacturer: "SonicWall",
        Model: "TZ670",
        Slug: "sonicwall-tz670",
        UHeight: 1,
        PartNumber: "TZ670",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 60, AllocatedDraw: 0 },
            { Name: "PSU 2", Label: "", Type: "iec-60320-c14", MaximumDraw: 60, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "X0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "X8", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X9", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
}
