// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapA10 = map[string]*DeviceData{
    "Thunder 4440 ADC": {
        Manufacturer: "A10",
        Model: "Thunder 4440 ADC",
        Slug: "a10-thunder-4440-adc",
        UHeight: 1,
        PartNumber: "TH4440",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "iec-60320-c14", MaximumDraw: 445, AllocatedDraw: 0 },
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 445, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "ipmi", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth5", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth6", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth7", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth8", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth9", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth10", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth11", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth12", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth13", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth14", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth15", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth16", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth17", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth18", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth19", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth20", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth21", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth22", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth23", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth24", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth25", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "eth26", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "eth27", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "eth28", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
        },
    },
    "Thunder 6430": {
        Manufacturer: "A10",
        Model: "Thunder 6430",
        Slug: "a10-thunder-6430",
        UHeight: 1,
        PartNumber: "TH6430",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "iec-60320-c14", MaximumDraw: 680, AllocatedDraw: 0 },
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 680, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "ipmi", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth5", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth6", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth7", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth8", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth9", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth10", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth11", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth12", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth13", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth14", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth15", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth16", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "eth17", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "eth18", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "eth19", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "eth20", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
        },
    },
}
