// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapQotom = map[string]*DeviceData{
    "Q330G4": {
        Manufacturer: "Qotom",
        Model: "Q330G4",
        Slug: "qotom-q330g4",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-5-15p", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
