// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapSedna = map[string]*DeviceData{
    "SE-RM-19-USB3-HUB-13-A": {
        Manufacturer: "Sedna",
        Model: "SE-RM-19-USB3-HUB-13-A",
        Slug: "sedna-usb3-hub-13p",
        UHeight: 1,
        PartNumber: "sedna-usb3-hub-13p",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "USB_1", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_2", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_3", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_4", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_5", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_6", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_7", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_8", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_9", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_10", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_11", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_12", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB_13", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "dc-terminal", MaximumDraw: 20, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
