// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapFactorTS = map[string]*DeviceData{
    "Dionis DPS-2004": {
        Manufacturer: "Factor-TS",
        Model: "Dionis DPS-2004",
        Slug: "factor-ts-dionis-dps-2004",
        UHeight: 1,
        PartNumber: "RM-4E",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU0", Label: "", Type: "iec-60320-c14", MaximumDraw: 50, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "ethernet 0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 3", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "Dionis DPS-3010-RM-6E-4S": {
        Manufacturer: "Factor-TS",
        Model: "Dionis DPS-3010-RM-6E-4S",
        Slug: "factor-ts-dionis-dps-3010-rm-6e-4s",
        UHeight: 1,
        PartNumber: "RM-6E-4S",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU0", Label: "", Type: "iec-60320-c14", MaximumDraw: 50, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "ethernet 0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "ethernet 6", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "ethernet 7", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "ethernet 8", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "ethernet 9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
}
