// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapNeousys = map[string]*DeviceData{
    "Nuvo-8240GC": {
        Manufacturer: "Neousys",
        Model: "Nuvo-8240GC",
        Slug: "neousys-nuvo-8240gc",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "COM 1", Type: "de-9", Label: "", Poe: false },
            { Name: "COM 2", Type: "de-9", Label: "", Poe: false },
            { Name: "DVI-D", Type: "other", Label: "", Poe: false },
            { Name: "DisplayPort", Type: "other", Label: "", Poe: false },
            { Name: "Audio 3.5m plug", Type: "other", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC", Label: "", Type: "dc-terminal", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "enp5s0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "enp0s31f6", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
