// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapSchneiderElectric = map[string]*DeviceData{
    "SpaceLogic AS-P-NL": {
        Manufacturer: "Schneider Electric",
        Model: "SpaceLogic AS-P-NL",
        Slug: "schneider-electric-spacelogic-as-p-nl",
        UHeight: 0,
        PartNumber: "SXWASPXXX10002",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 321,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "serial1", Type: "usb-mini-b", Label: "Device", Poe: false },
            { Name: "serial2", Type: "usb-micro-a", Label: "Host", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "power", Label: "Power", Type: "other", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1", Label: "Ethernet 1", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth2", Label: "Etrhernet 2", Type: "100base-tx", MgmtOnly: false },
        },
    },
}
