// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapVSolution = map[string]*DeviceData{
    "V1600D2": {
        Manufacturer: "V-Solution",
        Model: "V1600D2",
        Slug: "v-solution-v1600d2",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 25, AllocatedDraw: 20 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "gigabitethernet 0/1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "gigabitethernet 0/2", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "gigabitethernet 0/3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "gigabitethernet 0/4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "epon 0/1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "epon 0/2", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "aux", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
}
