// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapReichleDeMassari = map[string]*DeviceData{
    "19 1U HD Patch Panel 48-Port, black, empty": {
        Manufacturer: "Reichle &amp; De-Massari",
        Model: "19 1U HD Patch Panel 48-Port, black, empty",
        Slug: "reichle-and-de-massari-19-1u-hd-patch-panel-48-port-black-empty",
        UHeight: 1,
        PartNumber: "R512721",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "Slot 1", Label: "", Position: "1" },
            { Name: "Slot 2", Label: "", Position: "2" },
            { Name: "Slot 3", Label: "", Position: "3" },
            { Name: "Slot 4", Label: "", Position: "4" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
