// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapF5 = map[string]*DeviceData{
    "BIG-IP 2000": {
        Manufacturer: "F5",
        Model: "BIG-IP 2000",
        Slug: "f5-big-ip-2000",
        UHeight: 1,
        PartNumber: "2000",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 20,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "usb2", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "1" },
            { Name: "PSU2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "2.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "Failover", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "BIG-IP 3900": {
        Manufacturer: "F5",
        Model: "BIG-IP 3900",
        Slug: "f5-big-ip-3900",
        UHeight: 1,
        PartNumber: "3900",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "de-9", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "usb2", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 240, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 240, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "2.1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "2.2", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "2.3", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "2.4", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "BIG-IP 4200v": {
        Manufacturer: "F5",
        Model: "BIG-IP 4200v",
        Slug: "f5-big-ip-4200v",
        UHeight: 1,
        PartNumber: "4200v",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "usb2", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 155, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 155, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "2.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "BIG-IP 5200v": {
        Manufacturer: "F5",
        Model: "BIG-IP 5200v",
        Slug: "f5-big-ip-5200v",
        UHeight: 1,
        PartNumber: "5200v",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "usb2", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 245, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 245, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "2.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.5", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.6", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.7", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.8", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "BIG-IP 5250v": {
        Manufacturer: "F5",
        Model: "BIG-IP 5250v",
        Slug: "f5-big-ip-5250v",
        UHeight: 1,
        PartNumber: "5250v",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
            { Name: "serial failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 260, AllocatedDraw: 175 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 260, AllocatedDraw: 175 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "2.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.5", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.6", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.7", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.8", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "BIG-IP VPR-C2400": {
        Manufacturer: "F5",
        Model: "BIG-IP VPR-C2400",
        Slug: "f5-big-ip-vpr-c2400",
        UHeight: 4,
        PartNumber: "VPR-C2400",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "usb2", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c20", MaximumDraw: 1400, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c20", MaximumDraw: 1400, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "1/mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "BIG-IP i2600": {
        Manufacturer: "F5",
        Model: "BIG-IP i2600",
        Slug: "f5-big-ip-i2600",
        UHeight: 1,
        PartNumber: "i2600",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 120, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 120, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "2.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "3.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "4.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "5.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "6.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "BIG-IP i2800": {
        Manufacturer: "F5",
        Model: "BIG-IP i2800",
        Slug: "f5-big-ip-i2800",
        UHeight: 1,
        PartNumber: "i2800",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 120, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 120, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "2.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "3.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "4.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "5.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "6.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "BIG-IP i4600": {
        Manufacturer: "F5",
        Model: "BIG-IP i4600",
        Slug: "f5-big-ip-i4600",
        UHeight: 1,
        PartNumber: "i4600",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 165, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 165, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "2.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "3.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "4.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "5.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "6.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "7.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "8.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "9.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "10.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "11.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "12.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "BIG-IP i4800": {
        Manufacturer: "F5",
        Model: "BIG-IP i4800",
        Slug: "f5-big-ip-i4800",
        UHeight: 1,
        PartNumber: "i4800",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 165, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 165, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "2.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "3.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "4.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "5.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "6.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "7.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "8.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "9.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "10.0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "11.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "12.0", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "BIG-IP i5600": {
        Manufacturer: "F5",
        Model: "BIG-IP i5600",
        Slug: "f5-big-ip-i5600",
        UHeight: 1,
        PartNumber: "i5600",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 76,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "psu1", Label: "", Position: "1" },
            { Name: "psu2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "1.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "1.3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "1.4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "3.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "4.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "5.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "6.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "Failover", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "BIG-IP i5800": {
        Manufacturer: "F5",
        Model: "BIG-IP i5800",
        Slug: "f5-big-ip-i5800",
        UHeight: 1,
        PartNumber: "i5800",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Failover", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 330, AllocatedDraw: 0 },
            { Name: "psu2", Label: "", Type: "iec-60320-c14", MaximumDraw: 330, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "1.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "1.3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "1.4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2.4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "3.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "4.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "5.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
            { Name: "6.0", Label: "", Type: "40gbase-x-qsfpp", MgmtOnly: false },
        },
    },
    "BIG-IP r2600": {
        Manufacturer: "F5",
        Model: "BIG-IP r2600",
        Slug: "f5-big-ip-r2600",
        UHeight: 1,
        PartNumber: "r2600",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 20,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "1" },
            { Name: "PSU2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "failover", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1.0", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "2.0", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "3.0", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "4.0", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "5.0", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "6.0", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "7.0", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
            { Name: "8.0", Label: "", Type: "25gbase-x-sfp28", MgmtOnly: false },
        },
    },
}
