// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapIvanti = map[string]*DeviceData{
    "PulseSecure PSA300": {
        Manufacturer: "Ivanti",
        Model: "PulseSecure PSA300",
        Slug: "ivanti-pulse-secure-psa300",
        UHeight: 0,
        PartNumber: "PSA300",
        IsFullDepth: false,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1.13,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "dc-terminal", MaximumDraw: 37, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "internal", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "external", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "PulseSecure PSA3000": {
        Manufacturer: "Ivanti",
        Model: "PulseSecure PSA3000",
        Slug: "ivanti-pulse-secure-psa3000",
        UHeight: 1,
        PartNumber: "PSA3000",
        IsFullDepth: false,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 4.5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 47, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "internal", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "external", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "management", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "PulseSecure PSA5000": {
        Manufacturer: "Ivanti",
        Model: "PulseSecure PSA5000",
        Slug: "ivanti-pulse-secure-psa5000",
        UHeight: 1,
        PartNumber: "PSA5000",
        IsFullDepth: false,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 4.5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 83, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "internal", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "external", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "management", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "PulseSecure PSA7000c": {
        Manufacturer: "Ivanti",
        Model: "PulseSecure PSA7000c",
        Slug: "ivanti-pulse-secure-psa7000c",
        UHeight: 2,
        PartNumber: "PSA7000c",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 13.6,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "1" },
            { Name: "PSU2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "internal1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "internal2", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "external1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "external2", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "management", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "PulseSecure PSA7000f": {
        Manufacturer: "Ivanti",
        Model: "PulseSecure PSA7000f",
        Slug: "ivanti-pulse-secure-psa7000f",
        UHeight: 2,
        PartNumber: "PSA7000f",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 13.6,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "1" },
            { Name: "PSU2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "internal1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "internal2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "external1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "external2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "management", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
}
