// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapMoxa = map[string]*DeviceData{
    "EDS-408A-SS-SC-T": {
        Manufacturer: "Moxa",
        Model: "EDS-408A-SS-SC-T",
        Slug: "moxa-eds-408a-ss-sc-t",
        UHeight: 0,
        PartNumber: "EDS-408A-SS-SC-T",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: true,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 650,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "dc-terminal", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth4", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth5", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth6", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth7", Label: "", Type: "100base-fx", MgmtOnly: false },
            { Name: "eth8", Label: "", Type: "100base-fx", MgmtOnly: false },
        },
    },
    "EDS-P510": {
        Manufacturer: "Moxa",
        Model: "EDS-P510",
        Slug: "moxa-eds-p510",
        UHeight: 0,
        PartNumber: "EDS-P510",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: true,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1170,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "dc-terminal", MaximumDraw: 31, AllocatedDraw: 0 },
            { Name: "PS1", Label: "", Type: "dc-terminal", MaximumDraw: 31, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth4", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth5", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth6", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth7", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "G1-sfp", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "G1-rj45", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "G2-sfp", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "G2-rj45", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "G3-sfp", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "G3-rj45", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
