// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapInfinera = map[string]*DeviceData{
    "Cloud Xpress 2": {
        Manufacturer: "Infinera",
        Model: "Cloud Xpress 2",
        Slug: "infinera-cloud-xpress-2",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "con0", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "psu0", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "psu1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
            { Name: "rx-mux0", Label: "", Type: "lc", Positions: 1, Poe: false },
            { Name: "tx-mux0", Label: "", Type: "lc", Positions: 1, Poe: false },
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "swp1", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp2", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp3", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp4", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp5", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp6", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp7", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp8", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp9", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp10", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp11", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp12", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
        },
    },
}
