// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapRiverbed = map[string]*DeviceData{
    "CX1555": {
        Manufacturer: "Riverbed",
        Model: "CX1555",
        Slug: "riverbed-cx1555",
        UHeight: 1,
        PartNumber: "CX1555",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 450, AllocatedDraw: 175 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 450, AllocatedDraw: 175 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN_0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX3070": {
        Manufacturer: "Riverbed",
        Model: "CX3070",
        Slug: "riverbed-cx3070",
        UHeight: 1,
        PartNumber: "CX3070",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 527, AllocatedDraw: 422 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 527, AllocatedDraw: 422 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN3_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN3_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN3_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN3_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX5055": {
        Manufacturer: "Riverbed",
        Model: "CX5055",
        Slug: "riverbed-cx5055",
        UHeight: 2,
        PartNumber: "CX5055",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 770, AllocatedDraw: 375 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 770, AllocatedDraw: 375 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN_0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX555": {
        Manufacturer: "Riverbed",
        Model: "CX555",
        Slug: "riverbed-cx555",
        UHeight: 1,
        PartNumber: "CX555",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "other", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 45 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN_0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX570": {
        Manufacturer: "Riverbed",
        Model: "CX570",
        Slug: "riverbed-cx570",
        UHeight: 1,
        PartNumber: "CX570",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 45 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN_0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX7055": {
        Manufacturer: "Riverbed",
        Model: "CX7055",
        Slug: "riverbed-cx7055",
        UHeight: 2,
        PartNumber: "CX7055",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 770, AllocatedDraw: 420 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 770, AllocatedDraw: 420 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN_0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX7070": {
        Manufacturer: "Riverbed",
        Model: "CX7070",
        Slug: "riverbed-cx7070",
        UHeight: 2,
        PartNumber: "CX7070",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 527, AllocatedDraw: 422 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 527, AllocatedDraw: 422 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN1_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN1_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX755": {
        Manufacturer: "Riverbed",
        Model: "CX755",
        Slug: "riverbed-cx755",
        UHeight: 1,
        PartNumber: "CX755",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "other", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 50 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN_0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "CX770": {
        Manufacturer: "Riverbed",
        Model: "CX770",
        Slug: "riverbed-cx770",
        UHeight: 1,
        PartNumber: "CX770",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB0", Type: "usb-a", Label: "", Poe: false },
            { Name: "USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 50 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN_0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN0_1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Primary", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Aux", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
