// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapFujitsu = map[string]*DeviceData{
    "PRIMERGY RX2530 M6": {
        Manufacturer: "Fujitsu",
        Model: "PRIMERGY RX2530 M6",
        Slug: "fujitsu-primergy-rx2530-m6",
        UHeight: 1,
        PartNumber: "rx2530m6",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 18.2,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU-1", Label: "", Type: "iec-60320-c14", MaximumDraw: 900, AllocatedDraw: 0 },
            { Name: "PSU-2", Label: "", Type: "iec-60320-c14", MaximumDraw: 900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PCIe slot 1", Label: "1", Position: "PCIe-1" },
            { Name: "PCIe slot 2", Label: "2", Position: "PCIe-2" },
            { Name: "PCIe slot 3", Label: "3", Position: "PCIe-3" },
            { Name: "PCIe slot 4", Label: "4", Position: "PCIe-4" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "iRMC-S5", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "PRIMERGY RX2540 M5": {
        Manufacturer: "Fujitsu",
        Model: "PRIMERGY RX2540 M5",
        Slug: "fujitsu-primergy-rx2540-m5",
        UHeight: 2,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 25,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU-1", Label: "1", Position: "PSU-1" },
            { Name: "PSU-2", Label: "2", Position: "PSU-2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Gig-E 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Gig-E 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "TenGig-E 1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "TenGig-E 2", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "iRMC-S5", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "PRIMERGY TX100 S1": {
        Manufacturer: "Fujitsu",
        Model: "PRIMERGY TX100 S1",
        Slug: "fujitsu-primergy-tx100-s1",
        UHeight: 5,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 300, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Gig-E 1", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "PRIMERGY TX1310 M1": {
        Manufacturer: "Fujitsu",
        Model: "PRIMERGY TX1310 M1",
        Slug: "fujitsu-primergy-tx1310-m1",
        UHeight: 5,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 250, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Gig-E 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Gig-E 2", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "PRIMERGY TX1310 M3": {
        Manufacturer: "Fujitsu",
        Model: "PRIMERGY TX1310 M3",
        Slug: "fujitsu-primergy-tx1310-m3",
        UHeight: 5,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 250, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Gig-E 1", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "PRIMERGY TX1330 M4": {
        Manufacturer: "Fujitsu",
        Model: "PRIMERGY TX1330 M4",
        Slug: "fujitsu-primergy-tx1330-m4",
        UHeight: 5,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 250, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Gig-E 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Gig-E 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "iRMC-S5", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "Primergy BX2560 M1": {
        Manufacturer: "Fujitsu",
        Model: "Primergy BX2560 M1",
        Slug: "fujitsu-primergy-bx2560-m1",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "Front USB1", Type: "usb-a", Label: "" },
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "TenGig-E 1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "TenGig-E 2", Label: "", Type: "10gbase-t", MgmtOnly: false },
        },
    },
    "Primergy BX2560 M2": {
        Manufacturer: "Fujitsu",
        Model: "Primergy BX2560 M2",
        Slug: "fujitsu-primergy-bx2560-m2",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "Front USB1", Type: "usb-a", Label: "" },
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "TenGig-E 1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "TenGig-E 2", Label: "", Type: "10gbase-t", MgmtOnly: false },
        },
    },
    "Primergy BX924 S4": {
        Manufacturer: "Fujitsu",
        Model: "Primergy BX924 S4",
        Slug: "fujitsu-primergy-bx924-s4",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "Front USB1", Type: "usb-a", Label: "" },
            { Name: "Rear USB1", Type: "usb-a", Label: "" },
            { Name: "Rear USB2", Type: "usb-a", Label: "" },
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "TenGig-E 1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "TenGig-E 2", Label: "", Type: "10gbase-t", MgmtOnly: false },
        },
    },
}
