// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapRohdeSchwarz = map[string]*DeviceData{
    "SITLine ETH-L 10G": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "SITLine ETH-L 10G",
        Slug: "rohde-and-schwarz-sitline-eth-l-10g",
        UHeight: 1,
        PartNumber: "5414.6282.23",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "A1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "MGMT", Label: "", Type: "1000base-x-sfp", MgmtOnly: true },
        },
    },
    "SITLine ETH-L 4x10G": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "SITLine ETH-L 4x10G",
        Slug: "rohde-and-schwarz-sitline-eth-l-4x10g",
        UHeight: 1,
        PartNumber: "5414.6282.24",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "A1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "A2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "A3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "A4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "MGMT", Label: "", Type: "1000base-x-sfp", MgmtOnly: true },
        },
    },
    "SITLine ETH-L 4x1G": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "SITLine ETH-L 4x1G",
        Slug: "rohde-and-schwarz-sitline-eth-l-4x1g",
        UHeight: 1,
        PartNumber: "5414.6282.25",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "A1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "A2", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "A3", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "A4", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "MGMT", Label: "", Type: "1000base-x-sfp", MgmtOnly: true },
        },
    },
    "SITLine ETH-S 10G": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "SITLine ETH-S 10G",
        Slug: "rohde-and-schwarz-sitline-eth-s-10g",
        UHeight: 1,
        PartNumber: "5414.6260.23",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC-Input-A", Label: "DC-A", Type: "dc-terminal", MaximumDraw: 20, AllocatedDraw: 20 },
            { Name: "DC-Input-B", Label: "DC-B", Type: "dc-terminal", MaximumDraw: 20, AllocatedDraw: 20 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "A1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "SITLine ETH-S 1G": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "SITLine ETH-S 1G",
        Slug: "rohde-and-schwarz-sitline-eth-s-1g",
        UHeight: 1,
        PartNumber: "5414.6260.22",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC-Input-A", Label: "DC-A", Type: "dc-terminal", MaximumDraw: 20, AllocatedDraw: 20 },
            { Name: "DC-Input-B", Label: "DC-B", Type: "dc-terminal", MaximumDraw: 20, AllocatedDraw: 20 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "A1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "MGMT", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "SITLine ETH40G": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "SITLine ETH40G",
        Slug: "rohde-and-schwarz-sitline-eth40g",
        UHeight: 1,
        PartNumber: "5414.6130.02",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 80 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "A1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "A2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "A3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "A4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "SMS", Label: "", Type: "1000base-x-sfp", MgmtOnly: true },
        },
    },
    "SITLine ETH4G": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "SITLine ETH4G",
        Slug: "rohde-and-schwarz-sitline-eth4g",
        UHeight: 1,
        PartNumber: "5414.7766.02",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 65 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 100, AllocatedDraw: 65 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "A1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "A2", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "A3", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "A4", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X2", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X3", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "X4", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "SMS", Label: "", Type: "1000base-x-sfp", MgmtOnly: true },
        },
    },
    "TrustedVPN-L": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "TrustedVPN-L",
        Slug: "rohde-and-schwarz-trustedvpn-l",
        UHeight: 1,
        PartNumber: "3630.1751.02",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 150, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth7", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TrustedVPN-L VS-NfD": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "TrustedVPN-L VS-NfD",
        Slug: "rohde-and-schwarz-trustedvpn-l-vs-nfd",
        UHeight: 1,
        PartNumber: "3630.1751.13",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 150, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth7", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "TrustedVPN-XL": {
        Manufacturer: "Rohde &amp; Schwarz",
        Model: "TrustedVPN-XL",
        Slug: "rohde-and-schwarz-trustedvpn-xl",
        UHeight: 1,
        PartNumber: "3630.1768.02",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU1", Label: "", Type: "iec-60320-c14", MaximumDraw: 500, AllocatedDraw: 0 },
            { Name: "PSU2", Label: "", Type: "iec-60320-c14", MaximumDraw: 500, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
