// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapNEC = map[string]*DeviceData{
    "UNIVERGE IX2015": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2015",
        Slug: "nec-univerge-ix2015",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 12, AllocatedDraw: 12 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "BRI0 port S/T", Label: "", Type: "other", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2025": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2025",
        Slug: "nec-univerge-ix2025",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 9, AllocatedDraw: 9 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "FastEthernet0", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "FastEthernet1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "FastEthernet2 port 1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "FastEthernet2 port 2", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "FastEthernet2 port 3", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "FastEthernet2 port 4", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "BRI0 port LINE", Label: "", Type: "other", MgmtOnly: false },
            { Name: "BRI0 port S/T", Label: "", Type: "other", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2105": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2105",
        Slug: "nec-univerge-ix2105",
        UHeight: 1,
        PartNumber: "BE108821",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0.8,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 7, AllocatedDraw: 7 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2106": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2106",
        Slug: "nec-univerge-ix2106",
        UHeight: 1,
        PartNumber: "BI000087",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 7, AllocatedDraw: 7 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2107": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2107",
        Slug: "nec-univerge-ix2107",
        UHeight: 1,
        PartNumber: "BI000118",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 7, AllocatedDraw: 7 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1 port 4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2207": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2207",
        Slug: "nec-univerge-ix2207",
        UHeight: 1,
        PartNumber: "BI000059",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 24, AllocatedDraw: 11 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2 port 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2 port 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2 port 3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2 port 4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "USB0", Label: "", Type: "lte", MgmtOnly: false },
            { Name: "USB1", Label: "", Type: "lte", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2215": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2215",
        Slug: "nec-univerge-ix2215",
        UHeight: 1,
        PartNumber: "BI000054",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 18, AllocatedDraw: 14 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "USB0", Label: "", Type: "other", MgmtOnly: false },
            { Name: "BRI0 port LINE", Label: "", Type: "other", MgmtOnly: false },
            { Name: "BRI0 port S/T", Label: "", Type: "other", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2235": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2235",
        Slug: "nec-univerge-ix2235",
        UHeight: 1,
        PartNumber: "BI000106",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 19, AllocatedDraw: 12 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "USB0", Label: "", Type: "other", MgmtOnly: false },
        },
    },
    "UNIVERGE IX2310": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX2310",
        Slug: "nec-univerge-ix2310",
        UHeight: 1,
        PartNumber: "BI000111",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 50, AllocatedDraw: 42 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "USB0", Label: "", Type: "other", MgmtOnly: false },
        },
    },
    "UNIVERGE IX3110": {
        Manufacturer: "NEC",
        Model: "UNIVERGE IX3110",
        Slug: "nec-univerge-ix3110",
        UHeight: 1,
        PartNumber: "BE105556",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "Power Supply Slot 0", Label: "PSU 0", Position: "0" },
            { Name: "Power Supply Slot 1", Label: "PSU 1", Position: "1" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GigaEthernet0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "GigaEthernet3", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
