// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapSolidOptics = map[string]*DeviceData{
    "SO-CHASSIS-MOD4": {
        Manufacturer: "Solid Optics",
        Model: "SO-CHASSIS-MOD4",
        Slug: "solid-optics-so-chassis-mod4",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
            { Name: "Lower Left", Label: "" },
            { Name: "Lower Right", Label: "" },
            { Name: "Upper left", Label: "" },
            { Name: "Upper Right", Label: "" },
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "SO-DWDM-MUX-8CH&#43;UPG": {
        Manufacturer: "Solid Optics",
        Model: "SO-DWDM-MUX-8CH&#43;UPG",
        Slug: "solid-optics-so-dwdm-mux-8ch-plus-upg",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
            { Name: "C20", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 1 },
            { Name: "C21", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 2 },
            { Name: "C22", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 3 },
            { Name: "C23", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 4 },
            { Name: "C24", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 5 },
            { Name: "C25", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 6 },
            { Name: "C26", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 7 },
            { Name: "C27", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 8 },
            { Name: "UPG", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 9 },
        },
        RearPorts: []RearPort{
            { Name: "COM", Label: "", Type: "lc", Positions: 9, Poe: false },
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "SO-DWDM-MUX-CH20-35&#43;UPG&#43;MON": {
        Manufacturer: "Solid Optics",
        Model: "SO-DWDM-MUX-CH20-35&#43;UPG&#43;MON",
        Slug: "solid-optics-so-dwdm-mux-ch20-35-plus-upg-plus-mon",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
            { Name: "C20", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 2 },
            { Name: "C21", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 3 },
            { Name: "C22", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 4 },
            { Name: "C23", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 5 },
            { Name: "C24", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 6 },
            { Name: "C25", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 7 },
            { Name: "C26", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 8 },
            { Name: "C27", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 9 },
            { Name: "C28", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 10 },
            { Name: "C29", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 11 },
            { Name: "C30", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 12 },
            { Name: "C31", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 13 },
            { Name: "C32", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 14 },
            { Name: "C33", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 15 },
            { Name: "C34", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 16 },
            { Name: "C35", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 17 },
            { Name: "MON", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 1 },
            { Name: "UPG", Label: "", Type: "lc", RearPort: "COM", RearPortPosition: 18 },
        },
        RearPorts: []RearPort{
            { Name: "COM", Label: "", Type: "lc", Positions: 18, Poe: false },
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "SO-MOD4-3xMPO/MMF-24xLC": {
        Manufacturer: "Solid Optics",
        Model: "SO-MOD4-3xMPO/MMF-24xLC",
        Slug: "solid-optics-so-mod4-3xmpo-mmf-24xlc",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
            { Name: "A1", Label: "", Type: "lc", RearPort: "A", RearPortPosition: 1 },
            { Name: "A2", Label: "", Type: "lc", RearPort: "A", RearPortPosition: 2 },
            { Name: "A3", Label: "", Type: "lc", RearPort: "A", RearPortPosition: 3 },
            { Name: "A4", Label: "", Type: "lc", RearPort: "A", RearPortPosition: 4 },
            { Name: "B1", Label: "", Type: "lc", RearPort: "B", RearPortPosition: 1 },
            { Name: "B2", Label: "", Type: "lc", RearPort: "B", RearPortPosition: 2 },
            { Name: "B3", Label: "", Type: "lc", RearPort: "B", RearPortPosition: 3 },
            { Name: "B4", Label: "", Type: "lc", RearPort: "B", RearPortPosition: 4 },
            { Name: "C1", Label: "", Type: "lc", RearPort: "C", RearPortPosition: 1 },
            { Name: "C2", Label: "", Type: "lc", RearPort: "C", RearPortPosition: 2 },
            { Name: "C3", Label: "", Type: "lc", RearPort: "C", RearPortPosition: 3 },
            { Name: "C4", Label: "", Type: "lc", RearPort: "C", RearPortPosition: 4 },
        },
        RearPorts: []RearPort{
            { Name: "A", Label: "", Type: "mpo", Positions: 4, Poe: false },
            { Name: "B", Label: "", Type: "mpo", Positions: 4, Poe: false },
            { Name: "C", Label: "", Type: "mpo", Positions: 4, Poe: false },
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
