// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapLenovo = map[string]*DeviceData{
    "Flex System": {
        Manufacturer: "Lenovo",
        Model: "Flex System",
        Slug: "lenovo-flex-system",
        UHeight: 10,
        PartNumber: "8721W3X",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU0", Label: "", Type: "iec-60320-c20", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU1", Label: "", Type: "iec-60320-c20", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU2", Label: "", Type: "iec-60320-c20", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU3", Label: "", Type: "iec-60320-c20", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU4", Label: "", Type: "iec-60320-c20", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU5", Label: "", Type: "iec-60320-c20", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
            { Name: "Bay 1", Label: "" },
            { Name: "Bay 2", Label: "" },
            { Name: "Bay 3", Label: "" },
            { Name: "Bay 4", Label: "" },
            { Name: "Bay 5", Label: "" },
            { Name: "Bay 6", Label: "" },
            { Name: "Bay 7", Label: "" },
            { Name: "Bay 8", Label: "" },
            { Name: "Bay 9", Label: "" },
            { Name: "Bay 10", Label: "" },
            { Name: "Bay 11", Label: "" },
            { Name: "Bay 12", Label: "" },
            { Name: "Bay 13", Label: "" },
            { Name: "Bay 14", Label: "" },
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "CMM", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "System x3250 M6": {
        Manufacturer: "Lenovo",
        Model: "System x3250 M6",
        Slug: "lenovo-system-x3250-m6",
        UHeight: 1,
        PartNumber: "3633",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU 2", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "System x3550 M5": {
        Manufacturer: "Lenovo",
        Model: "System x3550 M5",
        Slug: "lenovo-system-x3550-m5",
        UHeight: 1,
        PartNumber: "5463AC1",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU 2", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "IMM", Label: "", Type: "100base-tx", MgmtOnly: true },
        },
    },
    "System x3750 M4": {
        Manufacturer: "Lenovo",
        Model: "System x3750 M4",
        Slug: "lenovo-system-x3750-m4",
        UHeight: 2,
        PartNumber: "8722C1U",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU 2", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "IMM", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkAgile MX3531-F CN": {
        Manufacturer: "Lenovo",
        Model: "ThinkAgile MX3531-F CN",
        Slug: "lenovo-thinkagile-mx3531-f-cn",
        UHeight: 2,
        PartNumber: "7D66",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 38.8,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU-1", Label: "", Position: "PSU-1" },
            { Name: "PSU-2", Label: "", Position: "PSU-2" },
            { Name: "OCP slot 1", Label: "", Position: "OCP-1" },
            { Name: "Riser 1 - PCIe slot 1", Label: "1 PCIe", Position: "PCIe-1" },
            { Name: "Riser 1 - PCIe slot 2", Label: "2 PCIe", Position: "PCIe-2" },
            { Name: "Riser 1 - PCIe slot 3", Label: "3 PCIe", Position: "PCIe-3" },
            { Name: "Riser 2 - PCIe slot 4", Label: "4 PCIe", Position: "PCIe-4" },
            { Name: "Riser 2 - PCIe slot 5", Label: "5 PCIe", Position: "PCIe-5" },
            { Name: "Riser 2 - PCIe slot 6", Label: "6 PCIe", Position: "PCIe-6" },
            { Name: "Riser 3 - PCIe slot 7", Label: "7 PCIe", Position: "PCIe-7" },
            { Name: "Riser 3 - PCIe slot 8", Label: "8 PCIe", Position: "PCIe-8" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkSystem 10Gb 2-port SFP&#43; LOM": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem 10Gb 2-port SFP&#43; LOM",
        Slug: "lenovo-thinksystem-10gb-2-port-sfpp-lom",
        UHeight: 0,
        PartNumber: "7ZT7A00546",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "1", Label: "1", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2", Label: "2", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "ThinkSystem 10Gb 4-port SFP&#43; LOM": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem 10Gb 4-port SFP&#43; LOM",
        Slug: "lenovo-thinksystem-10gb-4-port-sfpp-lom",
        UHeight: 0,
        PartNumber: "7ZT7A00547",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "1", Label: "1", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "2", Label: "2", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "3", Label: "3", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "4", Label: "4", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "ThinkSystem SR530": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem SR530",
        Slug: "lenovo-thinksystem-sr530",
        UHeight: 1,
        PartNumber: "7X07",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU0", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkSystem SR550": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem SR550",
        Slug: "lenovo-thinksystem-sr550",
        UHeight: 2,
        PartNumber: "7X04",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU0", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "Ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkSystem SR630": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem SR630",
        Slug: "lenovo-thinksystem-sr630",
        UHeight: 0,
        PartNumber: "7X02",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU0", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkSystem SR645": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem SR645",
        Slug: "lenovo-thinksystem-sr645",
        UHeight: 1,
        PartNumber: "7D2X",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 20.2,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU 1", Label: "", Position: "PSU1" },
            { Name: "PSU 2", Label: "", Position: "PSU2" },
            { Name: "OCP3", Label: "", Position: "OCP3" },
            { Name: "PCIe1", Label: "", Position: "Slot1" },
            { Name: "PCIe2", Label: "", Position: "Slot2" },
            { Name: "PCIe3", Label: "", Position: "Slot3" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkSystem SR650": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem SR650",
        Slug: "lenovo-thinksystem-sr650",
        UHeight: 2,
        PartNumber: "7X06",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU0", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "PSU1", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkSystem SR650 V2": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem SR650 V2",
        Slug: "lenovo-thinksystem-sr650-v2",
        UHeight: 2,
        PartNumber: "7Z7x",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 38.8,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU-1", Label: "", Position: "PSU-1" },
            { Name: "PSU-2", Label: "", Position: "PSU-2" },
            { Name: "OCP slot 1", Label: "", Position: "OCP-1" },
            { Name: "Riser 1 - PCIe slot 1", Label: "1 PCIe", Position: "PCIe-1" },
            { Name: "Riser 1 - PCIe slot 2", Label: "2 PCIe", Position: "PCIe-2" },
            { Name: "Riser 1 - PCIe slot 3", Label: "3 PCIe", Position: "PCIe-3" },
            { Name: "Riser 2 - PCIe slot 4", Label: "4 PCIe", Position: "PCIe-4" },
            { Name: "Riser 2 - PCIe slot 5", Label: "5 PCIe", Position: "PCIe-5" },
            { Name: "Riser 2 - PCIe slot 6", Label: "6 PCIe", Position: "PCIe-6" },
            { Name: "Riser 3 - PCIe slot 7", Label: "7 PCIe", Position: "PCIe-7" },
            { Name: "Riser 3 - PCIe slot 8", Label: "8 PCIe", Position: "PCIe-8" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ThinkSystem SR850 V2": {
        Manufacturer: "Lenovo",
        Model: "ThinkSystem SR850 V2",
        Slug: "lenovo-thinksystem-sr850-v2",
        UHeight: 2,
        PartNumber: "7D32",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 40,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU 1", Label: "", Position: "PSU1" },
            { Name: "PSU 2", Label: "", Position: "PSU2" },
            { Name: "PCIe1", Label: "", Position: "Slot1" },
            { Name: "PCIe2", Label: "", Position: "Slot2" },
            { Name: "PCIe3", Label: "", Position: "Slot3" },
            { Name: "OCP3", Label: "", Position: "Slot4" },
            { Name: "PCIe5", Label: "", Position: "Slot5" },
            { Name: "PCIe6", Label: "", Position: "Slot6" },
            { Name: "PCIe7", Label: "", Position: "Slot7" },
            { Name: "PCIe8", Label: "", Position: "Slot8" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "XCC", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
}
