// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapTbao = map[string]*DeviceData{
    "MN58U": {
        Manufacturer: "T-bao",
        Model: "MN58U",
        Slug: "t-bao-mn58u",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "usb-c", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "wlan0", Label: "", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
}
