// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapBarracuda = map[string]*DeviceData{
    "F280B": {
        Manufacturer: "Barracuda",
        Model: "F280B",
        Slug: "barracuda-f280b",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2.1,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "External PS", Label: "", Type: "dc-terminal", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "p1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "s8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "F380": {
        Manufacturer: "Barracuda",
        Model: "F380",
        Slug: "barracuda-f380",
        UHeight: 1,
        PartNumber: "BNGF380B",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 5.9,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "p1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "F400B": {
        Manufacturer: "Barracuda",
        Model: "F400B",
        Slug: "barracuda-f400b",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 7.5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "p1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "F80B": {
        Manufacturer: "Barracuda",
        Model: "F80B",
        Slug: "barracuda-f80b",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "External PS", Label: "", Type: "dc-terminal", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "p1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "p5", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "Message Archiver 350": {
        Manufacturer: "Barracuda",
        Model: "Message Archiver 350",
        Slug: "barracuda-message-archiver-350",
        UHeight: 1,
        PartNumber: "BMA350A",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 33,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "1", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
