// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapCalix = map[string]*DeviceData{
    "E7-2": {
        Manufacturer: "Calix",
        Model: "E7-2",
        Slug: "calix-e7-2",
        UHeight: 1,
        PartNumber: "000-00372",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "slot 1", Label: "", Position: "1" },
            { Name: "slot 2", Label: "", Position: "2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "E7-20": {
        Manufacturer: "Calix",
        Model: "E7-20",
        Slug: "calix-e7-20",
        UHeight: 13,
        PartNumber: "100-02089",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "slot 1", Label: "", Position: "1" },
            { Name: "slot 2", Label: "", Position: "2" },
            { Name: "slot 3", Label: "", Position: "3" },
            { Name: "slot 4", Label: "", Position: "4" },
            { Name: "slot 5", Label: "", Position: "5" },
            { Name: "slot 6", Label: "", Position: "6" },
            { Name: "slot 7", Label: "", Position: "7" },
            { Name: "slot 8", Label: "", Position: "8" },
            { Name: "slot 9", Label: "", Position: "9" },
            { Name: "slot 10", Label: "", Position: "10" },
            { Name: "slot 11", Label: "", Position: "11" },
            { Name: "slot 12", Label: "", Position: "12" },
            { Name: "slot 13", Label: "", Position: "13" },
            { Name: "slot 14", Label: "", Position: "14" },
            { Name: "slot 15", Label: "", Position: "15" },
            { Name: "slot 16", Label: "", Position: "16" },
            { Name: "slot 17", Label: "", Position: "17" },
            { Name: "slot 18", Label: "", Position: "18" },
            { Name: "slot 19", Label: "", Position: "19" },
            { Name: "slot 20", Label: "", Position: "20" },
            { Name: "slot A", Label: "", Position: "A" },
            { Name: "slot B", Label: "", Position: "B" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt 1", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "mgmt 3A", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "mgmt 3B", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
}
