// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapAlbisElcon = map[string]*DeviceData{
    "BIG2862": {
        Manufacturer: "Albis-Elcon",
        Model: "BIG2862",
        Slug: "albis-elcon-big2862",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2.1,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 33, AllocatedDraw: 13 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "SDSL", Label: "", Type: "xdsl", MgmtOnly: false },
            { Name: "T3/T4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN1S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "WAN2S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN1S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN2S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN3S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN4S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN4", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "BIG4862": {
        Manufacturer: "Albis-Elcon",
        Model: "BIG4862",
        Slug: "albis-elcon-big4862",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 4.5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS1", Label: "", Type: "iec-60320-c14", MaximumDraw: 65, AllocatedDraw: 50 },
            { Name: "PS2", Label: "", Type: "iec-60320-c14", MaximumDraw: 65, AllocatedDraw: 50 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LCT", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "T3/T4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "WAN1S", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "WAN2S", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "LAN1S", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "LAN2S", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "LAN3S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN4S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN5S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN6S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN7S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN8S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN9S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN10S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN11S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN12S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN13S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN14S", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "LAN13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "LAN14", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
