// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapYAMAHA = map[string]*DeviceData{
    "SWX2110-16G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2110-16G",
        Slug: "yamaha-swx2110-16g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2110-5G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2110-5G",
        Slug: "yamaha-swx2110-5g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU1", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2110-8G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2110-8G",
        Slug: "yamaha-swx2110-8g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU1", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2110P-8G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2110P-8G",
        Slug: "yamaha-swx2110p-8g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 84, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2210-16G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2210-16G",
        Slug: "yamaha-swx2210-16g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 13, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2210-24G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2210-24G",
        Slug: "yamaha-swx2210-24g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 17, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.24", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2210-8G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2210-8G",
        Slug: "yamaha-swx2210-8g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2210P-10G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2210P-10G",
        Slug: "yamaha-swx2210p-10g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 169, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2210P-18G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2210P-18G",
        Slug: "yamaha-swx2210p-18g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 338, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2210P-28G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2210P-28G",
        Slug: "yamaha-swx2210p-28g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 508, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.24", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.25", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.26", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.27", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.28", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2220-10NT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2220-10NT",
        Slug: "yamaha-swx2220-10nt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 21, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "10gbase-t", MgmtOnly: false },
        },
    },
    "SWX2221P-10NT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2221P-10NT",
        Slug: "yamaha-swx2221p-10nt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 304, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "2.5gbase-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "10gbase-t", MgmtOnly: false },
        },
    },
    "SWX2310-10G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2310-10G",
        Slug: "yamaha-swx2310-10g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 12, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX2310-18GT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2310-18GT",
        Slug: "yamaha-swx2310-18gt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 19, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX2310-28GT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2310-28GT",
        Slug: "yamaha-swx2310-28gt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 26, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.24", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.25", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.26", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.27", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.28", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX2310-52GT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2310-52GT",
        Slug: "yamaha-swx2310-52gt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 49, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.24", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.25", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.26", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.27", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.28", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.29", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.30", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.31", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.32", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.33", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.34", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.35", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.36", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.37", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.38", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.39", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.40", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.41", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.42", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.43", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.44", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.45", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.46", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.47", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.48", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.49", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.50", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.51", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.52", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX2310P-10G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2310P-10G",
        Slug: "yamaha-swx2310p-10g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 162, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2310P-18G": {
        Manufacturer: "YAMAHA",
        Model: "SWX2310P-18G",
        Slug: "yamaha-swx2310p-18g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 306, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SWX2310P-28GT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2310P-28GT",
        Slug: "yamaha-swx2310p-28gt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 459, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.24", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.25", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.26", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.27", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.28", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX2320-16MT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2320-16MT",
        Slug: "yamaha-swx2320-16mt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 84, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "SWX2322P-16MT": {
        Manufacturer: "YAMAHA",
        Model: "SWX2322P-16MT",
        Slug: "yamaha-swx2322p-16mt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 385, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "SWX3100-10G": {
        Manufacturer: "YAMAHA",
        Model: "SWX3100-10G",
        Slug: "yamaha-swx3100-10g",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 12, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX3100-18GT": {
        Manufacturer: "YAMAHA",
        Model: "SWX3100-18GT",
        Slug: "yamaha-swx3100-18gt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 19, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX3200-28GT": {
        Manufacturer: "YAMAHA",
        Model: "SWX3200-28GT",
        Slug: "yamaha-swx3200-28gt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 27, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.24", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.25", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.26", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.27", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.28", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX3200-52GT": {
        Manufacturer: "YAMAHA",
        Model: "SWX3200-52GT",
        Slug: "yamaha-swx3200-52gt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 48, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.24", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.25", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.26", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.27", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.28", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.29", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.30", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.31", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.32", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.33", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.34", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.35", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.36", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.37", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.38", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.39", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.40", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.41", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.42", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.43", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.44", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.45", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.46", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.47", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.48", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1.49", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.50", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.51", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1.52", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
    "SWX3220-16MT": {
        Manufacturer: "YAMAHA",
        Model: "SWX3220-16MT",
        Slug: "yamaha-swx3220-16mt",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 84, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.13", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.14", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.15", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.16", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
    "SWX3220-16TMs": {
        Manufacturer: "YAMAHA",
        Model: "SWX3220-16TMs",
        Slug: "yamaha-swx3220-16tms",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "RJ-45 console port", Type: "rj-45", Label: "", Poe: false },
            { Name: "USB console port", Type: "usb-mini-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 61, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port1.1", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.2", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.3", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.4", Label: "", Type: "10gbase-t", MgmtOnly: false },
            { Name: "port1.5", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.6", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.7", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.8", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.9", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.10", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.11", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
            { Name: "port1.12", Label: "", Type: "10gbase-x-sfpp", MgmtOnly: false },
        },
    },
}
