// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapLeviton = map[string]*DeviceData{
    "24 Port Keystone Patch Panel": {
        Manufacturer: "Leviton",
        Model: "24 Port Keystone Patch Panel",
        Slug: "leviton-24-port-keystone-patch-panel",
        UHeight: 1,
        PartNumber: "49255-H24",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "1", Label: "", Position: "1" },
            { Name: "2", Label: "", Position: "2" },
            { Name: "3", Label: "", Position: "3" },
            { Name: "4", Label: "", Position: "4" },
            { Name: "5", Label: "", Position: "5" },
            { Name: "6", Label: "", Position: "6" },
            { Name: "7", Label: "", Position: "7" },
            { Name: "8", Label: "", Position: "8" },
            { Name: "9", Label: "", Position: "9" },
            { Name: "10", Label: "", Position: "10" },
            { Name: "11", Label: "", Position: "11" },
            { Name: "12", Label: "", Position: "12" },
            { Name: "13", Label: "", Position: "13" },
            { Name: "14", Label: "", Position: "14" },
            { Name: "15", Label: "", Position: "15" },
            { Name: "16", Label: "", Position: "16" },
            { Name: "17", Label: "", Position: "17" },
            { Name: "18", Label: "", Position: "18" },
            { Name: "19", Label: "", Position: "19" },
            { Name: "20", Label: "", Position: "20" },
            { Name: "21", Label: "", Position: "21" },
            { Name: "22", Label: "", Position: "22" },
            { Name: "23", Label: "", Position: "23" },
            { Name: "24", Label: "", Position: "24" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "48 Port Keystone Patch Panel": {
        Manufacturer: "Leviton",
        Model: "48 Port Keystone Patch Panel",
        Slug: "leviton-48-port-keystone-patch-panel",
        UHeight: 1,
        PartNumber: "49255-Q48",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "1", Label: "", Position: "1" },
            { Name: "2", Label: "", Position: "2" },
            { Name: "3", Label: "", Position: "3" },
            { Name: "4", Label: "", Position: "4" },
            { Name: "5", Label: "", Position: "5" },
            { Name: "6", Label: "", Position: "6" },
            { Name: "7", Label: "", Position: "7" },
            { Name: "8", Label: "", Position: "8" },
            { Name: "9", Label: "", Position: "9" },
            { Name: "10", Label: "", Position: "10" },
            { Name: "11", Label: "", Position: "11" },
            { Name: "12", Label: "", Position: "12" },
            { Name: "13", Label: "", Position: "13" },
            { Name: "14", Label: "", Position: "14" },
            { Name: "15", Label: "", Position: "15" },
            { Name: "16", Label: "", Position: "16" },
            { Name: "17", Label: "", Position: "17" },
            { Name: "18", Label: "", Position: "18" },
            { Name: "19", Label: "", Position: "19" },
            { Name: "20", Label: "", Position: "20" },
            { Name: "21", Label: "", Position: "21" },
            { Name: "22", Label: "", Position: "22" },
            { Name: "23", Label: "", Position: "23" },
            { Name: "24", Label: "", Position: "24" },
            { Name: "25", Label: "", Position: "25" },
            { Name: "26", Label: "", Position: "26" },
            { Name: "27", Label: "", Position: "27" },
            { Name: "28", Label: "", Position: "28" },
            { Name: "29", Label: "", Position: "29" },
            { Name: "30", Label: "", Position: "30" },
            { Name: "31", Label: "", Position: "31" },
            { Name: "32", Label: "", Position: "32" },
            { Name: "33", Label: "", Position: "33" },
            { Name: "34", Label: "", Position: "34" },
            { Name: "35", Label: "", Position: "35" },
            { Name: "36", Label: "", Position: "36" },
            { Name: "37", Label: "", Position: "37" },
            { Name: "38", Label: "", Position: "38" },
            { Name: "39", Label: "", Position: "39" },
            { Name: "40", Label: "", Position: "40" },
            { Name: "41", Label: "", Position: "41" },
            { Name: "42", Label: "", Position: "42" },
            { Name: "43", Label: "", Position: "43" },
            { Name: "44", Label: "", Position: "44" },
            { Name: "45", Label: "", Position: "45" },
            { Name: "46", Label: "", Position: "46" },
            { Name: "47", Label: "", Position: "47" },
            { Name: "48", Label: "", Position: "48" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "5R1UM-F03": {
        Manufacturer: "Leviton",
        Model: "5R1UM-F03",
        Slug: "leviton-5r1um-f03",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "A", Label: "", Position: "A" },
            { Name: "B", Label: "", Position: "B" },
            { Name: "C", Label: "", Position: "C" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "5R2UM-F06": {
        Manufacturer: "Leviton",
        Model: "5R2UM-F06",
        Slug: "leviton-5r2um-f06",
        UHeight: 2,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "A", Label: "", Position: "A" },
            { Name: "B", Label: "", Position: "B" },
            { Name: "C", Label: "", Position: "C" },
            { Name: "D", Label: "", Position: "D" },
            { Name: "E", Label: "", Position: "E" },
            { Name: "F", Label: "", Position: "F" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "5R3UM-F09": {
        Manufacturer: "Leviton",
        Model: "5R3UM-F09",
        Slug: "leviton-5r3um-f09",
        UHeight: 3,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "A", Label: "", Position: "A" },
            { Name: "B", Label: "", Position: "B" },
            { Name: "C", Label: "", Position: "C" },
            { Name: "D", Label: "", Position: "D" },
            { Name: "E", Label: "", Position: "E" },
            { Name: "F", Label: "", Position: "F" },
            { Name: "G", Label: "", Position: "G" },
            { Name: "H", Label: "", Position: "H" },
            { Name: "I", Label: "", Position: "I" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "5R3UM-F12": {
        Manufacturer: "Leviton",
        Model: "5R3UM-F12",
        Slug: "leviton-5r3um-f12",
        UHeight: 3,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "A", Label: "", Position: "A" },
            { Name: "B", Label: "", Position: "B" },
            { Name: "C", Label: "", Position: "C" },
            { Name: "D", Label: "", Position: "D" },
            { Name: "E", Label: "", Position: "E" },
            { Name: "F", Label: "", Position: "F" },
            { Name: "G", Label: "", Position: "G" },
            { Name: "H", Label: "", Position: "H" },
            { Name: "I", Label: "", Position: "I" },
            { Name: "J", Label: "", Position: "J" },
            { Name: "K", Label: "", Position: "K" },
            { Name: "L", Label: "", Position: "L" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
