// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapMimosaNetworks = map[string]*DeviceData{
    "A5": {
        Manufacturer: "Mimosa Networks",
        Model: "A5",
        Slug: "mimosa-networks-a5",
        UHeight: 0,
        PartNumber: "a5",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
    "A5c": {
        Manufacturer: "Mimosa Networks",
        Model: "A5c",
        Slug: "mimosa-networks-a5c",
        UHeight: 0,
        PartNumber: "a5c",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
    "A5x": {
        Manufacturer: "Mimosa Networks",
        Model: "A5x",
        Slug: "mimosa-networks-a5x",
        UHeight: 0,
        PartNumber: "a5x",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
    "B5X": {
        Manufacturer: "Mimosa Networks",
        Model: "B5X",
        Slug: "mimosa-networks-b5x",
        UHeight: 0,
        PartNumber: "b5x",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
            { Name: "wifi1", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
    "B5c": {
        Manufacturer: "Mimosa Networks",
        Model: "B5c",
        Slug: "mimosa-networks-b5c",
        UHeight: 0,
        PartNumber: "b5c",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
            { Name: "wifi1", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
    "C5c": {
        Manufacturer: "Mimosa Networks",
        Model: "C5c",
        Slug: "mimosa-networks-c5c",
        UHeight: 0,
        PartNumber: "C5c",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
    "C5x": {
        Manufacturer: "Mimosa Networks",
        Model: "C5x",
        Slug: "mimosa-networks-c5x",
        UHeight: 0,
        PartNumber: "C5x",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
    "C6x": {
        Manufacturer: "Mimosa Networks",
        Model: "C6x",
        Slug: "mimosa-networks-c6x",
        UHeight: 0,
        PartNumber: "C6x",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth1_emac1", Label: "Ethernet", Type: "1000base-t", MgmtOnly: false },
            { Name: "wifi0", Label: "Wireless", Type: "ieee802.11ax", MgmtOnly: false },
        },
    },
}
