name: scan
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@e5d8bc7c23180f3e45d302225c0ebe942f963140 # main
