name: scan
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@bc53d0696520814daccfecff84b00e4d1391acdd # main
