name: scan
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@6649a90f53072076177e4a2aa5226b35c04ca1cb # main
