name: OSV-Scanner PR Scan
on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

permissions:
  # Required to upload SARIF file to CodeQL.
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan-pr:
    uses: bl4ko/shared-actions/.github/workflows/osv.yml@8b0a64af7fbe8059c9dea9f67b797776aae68c0c # main
