name: Create semantic tag
permissions:
  contents: read
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    uses: bl4ko/shared-actions/.github/workflows/release.yml@main
    secrets:
      SVC_TOKEN: ${{ secrets.SVC_TOKEN }}
