name: Check spelling with spellcheck
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
jobs:
  spellcheck:
    uses: bl4ko/shared-actions/.github/workflows/spellcheck.yml@376135da209e0470ef8e41b3e60d4b01d0b41ac6 # main
