name: Check spelling with spellcheck
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
jobs:
  spellcheck:
    uses: bl4ko/shared-actions/.github/workflows/spellcheck.yml@978de563c5ea8263b376c1dd96702f983ccfd607 # main
