name: Check spelling with spellcheck
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
jobs:
  spellcheck:
    uses: bl4ko/shared-actions/.github/workflows/spellcheck.yml@fd8861a73fea41140154ad4d186670647d5d4722 # main
